# Generated by Django 5.1.1 on 2024-10-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_personnel_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='service_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
