# Generated by Django 5.1.1 on 2024-10-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_personnel_service_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='service_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
