# Generated by Django 5.1.1 on 2024-10-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_personnel_service_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='surname',
        ),
        migrations.AddField(
            model_name='personnel',
            name='official_name',
            field=models.CharField(help_text='Full official name of the user.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
